version: '2.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "www-data:www-data"  
    ports:
      - '8089:8080'
    volumes:
       - './apps.csv:/usr/share/nginx/html/apps.csv'
